global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["65.0.177.208:9090"]

  - job_name: "node-exporter"
    static_configs:
    - targets: ["65.0.177.208:9100"]


    
  
